/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PromptLabRouteImport } from './routes/prompt-lab'
import { Route as PricingCalculatorRouteImport } from './routes/pricing-calculator'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolIdRouteImport } from './routes/tool.$id'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptLabRoute = PromptLabRouteImport.update({
  id: '/prompt-lab',
  path: '/prompt-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingCalculatorRoute = PricingCalculatorRouteImport.update({
  id: '/pricing-calculator',
  path: '/pricing-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolIdRoute = ToolIdRouteImport.update({
  id: '/tool/$id',
  path: '/tool/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/models': typeof ModelsRoute
  '/pricing-calculator': typeof PricingCalculatorRoute
  '/prompt-lab': typeof PromptLabRoute
  '/rankings': typeof RankingsRoute
  '/tools': typeof ToolsRoute
  '/tool/$id': typeof ToolIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/models': typeof ModelsRoute
  '/pricing-calculator': typeof PricingCalculatorRoute
  '/prompt-lab': typeof PromptLabRoute
  '/rankings': typeof RankingsRoute
  '/tools': typeof ToolsRoute
  '/tool/$id': typeof ToolIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/models': typeof ModelsRoute
  '/pricing-calculator': typeof PricingCalculatorRoute
  '/prompt-lab': typeof PromptLabRoute
  '/rankings': typeof RankingsRoute
  '/tools': typeof ToolsRoute
  '/tool/$id': typeof ToolIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/community'
    | '/compare'
    | '/models'
    | '/pricing-calculator'
    | '/prompt-lab'
    | '/rankings'
    | '/tools'
    | '/tool/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/community'
    | '/compare'
    | '/models'
    | '/pricing-calculator'
    | '/prompt-lab'
    | '/rankings'
    | '/tools'
    | '/tool/$id'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/community'
    | '/compare'
    | '/models'
    | '/pricing-calculator'
    | '/prompt-lab'
    | '/rankings'
    | '/tools'
    | '/tool/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  CommunityRoute: typeof CommunityRoute
  CompareRoute: typeof CompareRoute
  ModelsRoute: typeof ModelsRoute
  PricingCalculatorRoute: typeof PricingCalculatorRoute
  PromptLabRoute: typeof PromptLabRoute
  RankingsRoute: typeof RankingsRoute
  ToolsRoute: typeof ToolsRoute
  ToolIdRoute: typeof ToolIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-lab': {
      id: '/prompt-lab'
      path: '/prompt-lab'
      fullPath: '/prompt-lab'
      preLoaderRoute: typeof PromptLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing-calculator': {
      id: '/pricing-calculator'
      path: '/pricing-calculator'
      fullPath: '/pricing-calculator'
      preLoaderRoute: typeof PricingCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/$id': {
      id: '/tool/$id'
      path: '/tool/$id'
      fullPath: '/tool/$id'
      preLoaderRoute: typeof ToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  CommunityRoute: CommunityRoute,
  CompareRoute: CompareRoute,
  ModelsRoute: ModelsRoute,
  PricingCalculatorRoute: PricingCalculatorRoute,
  PromptLabRoute: PromptLabRoute,
  RankingsRoute: RankingsRoute,
  ToolsRoute: ToolsRoute,
  ToolIdRoute: ToolIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
