insert into public.ai_categories (slug,name,description) values
  ('chatbots-general-llms','Chatbots & General LLMs','Initial verified catalog category: Chatbots & General LLMs'),
  ('coding-assistants','Coding Assistants','Initial verified catalog category: Coding Assistants'),
  ('ai-ides','AI IDEs','Initial verified catalog category: AI IDEs'),
  ('research-search','Research & Search','Initial verified catalog category: Research & Search'),
  ('image-generation','Image Generation','Initial verified catalog category: Image Generation'),
  ('video-generation','Video Generation','Initial verified catalog category: Video Generation'),
  ('voice-audio-music','Voice, Audio & Music','Initial verified catalog category: Voice, Audio & Music'),
  ('agents-automation','Agents & Automation','Initial verified catalog category: Agents & Automation'),
  ('productivity','Productivity','Initial verified catalog category: Productivity'),
  ('design-ui','Design & UI','Initial verified catalog category: Design & UI'),
  ('marketing-writing','Marketing & Writing','Initial verified catalog category: Marketing & Writing'),
  ('education','Education','Initial verified catalog category: Education'),
  ('data-analysis','Data Analysis','Initial verified catalog category: Data Analysis'),
  ('open-source-models','Open-Source Models','Initial verified catalog category: Open-Source Models'),
  ('ai-infrastructure-apis','AI Infrastructure & APIs','Initial verified catalog category: AI Infrastructure & APIs'),
  ('business-enterprise','Business & Enterprise','Initial verified catalog category: Business & Enterprise')
on conflict (slug) do update set name = excluded.name, description = excluded.description, updated_at = now();

with category_map as (select id, slug from public.ai_categories)
insert into public.ai_tools (slug,name,tagline,description,category_id,subcategory,website_url,logo_url,pricing_type,starting_price,free_plan,best_for,strengths,weaknesses,supported_platforms,open_source,api_available,featured,editor_pick,last_verified_at)
values
  ('chatgpt-1','ChatGPT 1','Production starter catalog entry','Initial editorial profile for ChatGPT 1 in Chatbots & General LLMs.',(select id from category_map where slug = 'chatbots-general-llms'),'Core','https://example.com/chatgpt-1','icon-1','Free',null,true,'Teams evaluating chatbots & general llms','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,true,true,now() - interval '0 days'),
  ('claude-2','Claude 2','Production starter catalog entry','Initial editorial profile for Claude 2 in Coding Assistants.',(select id from category_map where slug = 'coding-assistants'),'Core','https://example.com/claude-2','icon-2','Freemium',6.00,true,'Teams evaluating coding assistants','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '1 days'),
  ('gemini-3','Gemini 3','Production starter catalog entry','Initial editorial profile for Gemini 3 in AI IDEs.',(select id from category_map where slug = 'ai-ides'),'Core','https://example.com/gemini-3','icon-3','Paid',7.00,false,'Teams evaluating ai ides','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '2 days'),
  ('grok-4','Grok 4','Production starter catalog entry','Initial editorial profile for Grok 4 in Research & Search.',(select id from category_map where slug = 'research-search'),'Core','https://example.com/grok-4','icon-4','Open Source',null,true,'Teams evaluating research & search','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '3 days'),
  ('perplexity-5','Perplexity 5','Production starter catalog entry','Initial editorial profile for Perplexity 5 in Image Generation.',(select id from category_map where slug = 'image-generation'),'Core','https://example.com/perplexity-5','icon-5','Enterprise',9.00,false,'Teams evaluating image generation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '4 days'),
  ('cursor-6','Cursor 6','Production starter catalog entry','Initial editorial profile for Cursor 6 in Video Generation.',(select id from category_map where slug = 'video-generation'),'Core','https://example.com/cursor-6','icon-6','Free',null,true,'Teams evaluating video generation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '5 days'),
  ('windsurf-7','Windsurf 7','Production starter catalog entry','Initial editorial profile for Windsurf 7 in Voice, Audio & Music.',(select id from category_map where slug = 'voice-audio-music'),'Core','https://example.com/windsurf-7','icon-7','Freemium',11.00,true,'Teams evaluating voice, audio & music','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '6 days'),
  ('midjourney-8','Midjourney 8','Production starter catalog entry','Initial editorial profile for Midjourney 8 in Agents & Automation.',(select id from category_map where slug = 'agents-automation'),'Core','https://example.com/midjourney-8','icon-8','Paid',12.00,false,'Teams evaluating agents & automation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '7 days'),
  ('runway-9','Runway 9','Production starter catalog entry','Initial editorial profile for Runway 9 in Productivity.',(select id from category_map where slug = 'productivity'),'Core','https://example.com/runway-9','icon-9','Open Source',null,true,'Teams evaluating productivity','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '8 days'),
  ('copilot-10','GitHub Copilot 10','Production starter catalog entry','Initial editorial profile for GitHub Copilot 10 in Design & UI.',(select id from category_map where slug = 'design-ui'),'Core','https://example.com/copilot-10','icon-10','Enterprise',14.00,false,'Teams evaluating design & ui','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '9 days'),
  ('notion-ai-11','Notion AI 11','Production starter catalog entry','Initial editorial profile for Notion AI 11 in Marketing & Writing.',(select id from category_map where slug = 'marketing-writing'),'Core','https://example.com/notion-ai-11','icon-11','Free',null,true,'Teams evaluating marketing & writing','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,true,false,now() - interval '10 days'),
  ('jasper-12','Jasper 12','Production starter catalog entry','Initial editorial profile for Jasper 12 in Education.',(select id from category_map where slug = 'education'),'Core','https://example.com/jasper-12','icon-12','Freemium',16.00,true,'Teams evaluating education','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '11 days'),
  ('canva-ai-13','Canva AI 13','Production starter catalog entry','Initial editorial profile for Canva AI 13 in Data Analysis.',(select id from category_map where slug = 'data-analysis'),'Core','https://example.com/canva-ai-13','icon-1','Paid',17.00,false,'Teams evaluating data analysis','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '12 days'),
  ('suno-14','Suno 14','Production starter catalog entry','Initial editorial profile for Suno 14 in Open-Source Models.',(select id from category_map where slug = 'open-source-models'),'Core','https://example.com/suno-14','icon-2','Open Source',null,true,'Teams evaluating open-source models','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '13 days'),
  ('elevenlabs-15','ElevenLabs 15','Production starter catalog entry','Initial editorial profile for ElevenLabs 15 in AI Infrastructure & APIs.',(select id from category_map where slug = 'ai-infrastructure-apis'),'Core','https://example.com/elevenlabs-15','icon-3','Enterprise',19.00,false,'Teams evaluating ai infrastructure & apis','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,true,now() - interval '14 days'),
  ('stable-diffusion-16','Stable Diffusion 16','Production starter catalog entry','Initial editorial profile for Stable Diffusion 16 in Business & Enterprise.',(select id from category_map where slug = 'business-enterprise'),'Core','https://example.com/stable-diffusion-16','icon-4','Free',null,true,'Teams evaluating business & enterprise','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '15 days'),
  ('llama-17','Llama 17','Production starter catalog entry','Initial editorial profile for Llama 17 in Chatbots & General LLMs.',(select id from category_map where slug = 'chatbots-general-llms'),'Core','https://example.com/llama-17','icon-5','Freemium',21.00,true,'Teams evaluating chatbots & general llms','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '16 days'),
  ('mistral-18','Mistral 18','Production starter catalog entry','Initial editorial profile for Mistral 18 in Coding Assistants.',(select id from category_map where slug = 'coding-assistants'),'Core','https://example.com/mistral-18','icon-6','Paid',22.00,false,'Teams evaluating coding assistants','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '17 days'),
  ('huggingface-19','Hugging Face 19','Production starter catalog entry','Initial editorial profile for Hugging Face 19 in AI IDEs.',(select id from category_map where slug = 'ai-ides'),'Core','https://example.com/huggingface-19','icon-7','Open Source',null,true,'Teams evaluating ai ides','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '18 days'),
  ('n8n-ai-20','n8n AI 20','Production starter catalog entry','Initial editorial profile for n8n AI 20 in Research & Search.',(select id from category_map where slug = 'research-search'),'Core','https://example.com/n8n-ai-20','icon-8','Enterprise',24.00,false,'Teams evaluating research & search','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '19 days'),
  ('chatgpt-21','ChatGPT 21','Production starter catalog entry','Initial editorial profile for ChatGPT 21 in Image Generation.',(select id from category_map where slug = 'image-generation'),'Core','https://example.com/chatgpt-21','icon-9','Free',null,true,'Teams evaluating image generation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,true,false,now() - interval '20 days'),
  ('claude-22','Claude 22','Production starter catalog entry','Initial editorial profile for Claude 22 in Video Generation.',(select id from category_map where slug = 'video-generation'),'Core','https://example.com/claude-22','icon-10','Freemium',26.00,true,'Teams evaluating video generation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '21 days'),
  ('gemini-23','Gemini 23','Production starter catalog entry','Initial editorial profile for Gemini 23 in Voice, Audio & Music.',(select id from category_map where slug = 'voice-audio-music'),'Core','https://example.com/gemini-23','icon-11','Paid',27.00,false,'Teams evaluating voice, audio & music','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '22 days'),
  ('grok-24','Grok 24','Production starter catalog entry','Initial editorial profile for Grok 24 in Agents & Automation.',(select id from category_map where slug = 'agents-automation'),'Core','https://example.com/grok-24','icon-12','Open Source',null,true,'Teams evaluating agents & automation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '23 days'),
  ('perplexity-25','Perplexity 25','Production starter catalog entry','Initial editorial profile for Perplexity 25 in Productivity.',(select id from category_map where slug = 'productivity'),'Core','https://example.com/perplexity-25','icon-1','Enterprise',29.00,false,'Teams evaluating productivity','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '24 days'),
  ('cursor-26','Cursor 26','Production starter catalog entry','Initial editorial profile for Cursor 26 in Design & UI.',(select id from category_map where slug = 'design-ui'),'Core','https://example.com/cursor-26','icon-2','Free',null,true,'Teams evaluating design & ui','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '25 days'),
  ('windsurf-27','Windsurf 27','Production starter catalog entry','Initial editorial profile for Windsurf 27 in Marketing & Writing.',(select id from category_map where slug = 'marketing-writing'),'Core','https://example.com/windsurf-27','icon-3','Freemium',6.00,true,'Teams evaluating marketing & writing','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '26 days'),
  ('midjourney-28','Midjourney 28','Production starter catalog entry','Initial editorial profile for Midjourney 28 in Education.',(select id from category_map where slug = 'education'),'Core','https://example.com/midjourney-28','icon-4','Paid',7.00,false,'Teams evaluating education','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '27 days'),
  ('runway-29','Runway 29','Production starter catalog entry','Initial editorial profile for Runway 29 in Data Analysis.',(select id from category_map where slug = 'data-analysis'),'Core','https://example.com/runway-29','icon-5','Open Source',null,true,'Teams evaluating data analysis','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,true,now() - interval '28 days'),
  ('copilot-30','GitHub Copilot 30','Production starter catalog entry','Initial editorial profile for GitHub Copilot 30 in Open-Source Models.',(select id from category_map where slug = 'open-source-models'),'Core','https://example.com/copilot-30','icon-6','Enterprise',9.00,false,'Teams evaluating open-source models','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '29 days'),
  ('notion-ai-31','Notion AI 31','Production starter catalog entry','Initial editorial profile for Notion AI 31 in AI Infrastructure & APIs.',(select id from category_map where slug = 'ai-infrastructure-apis'),'Core','https://example.com/notion-ai-31','icon-7','Free',null,true,'Teams evaluating ai infrastructure & apis','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,true,false,now() - interval '30 days'),
  ('jasper-32','Jasper 32','Production starter catalog entry','Initial editorial profile for Jasper 32 in Business & Enterprise.',(select id from category_map where slug = 'business-enterprise'),'Core','https://example.com/jasper-32','icon-8','Freemium',11.00,true,'Teams evaluating business & enterprise','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '31 days'),
  ('canva-ai-33','Canva AI 33','Production starter catalog entry','Initial editorial profile for Canva AI 33 in Chatbots & General LLMs.',(select id from category_map where slug = 'chatbots-general-llms'),'Core','https://example.com/canva-ai-33','icon-9','Paid',12.00,false,'Teams evaluating chatbots & general llms','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '32 days'),
  ('suno-34','Suno 34','Production starter catalog entry','Initial editorial profile for Suno 34 in Coding Assistants.',(select id from category_map where slug = 'coding-assistants'),'Core','https://example.com/suno-34','icon-10','Open Source',null,true,'Teams evaluating coding assistants','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '33 days'),
  ('elevenlabs-35','ElevenLabs 35','Production starter catalog entry','Initial editorial profile for ElevenLabs 35 in AI IDEs.',(select id from category_map where slug = 'ai-ides'),'Core','https://example.com/elevenlabs-35','icon-11','Enterprise',14.00,false,'Teams evaluating ai ides','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '34 days'),
  ('stable-diffusion-36','Stable Diffusion 36','Production starter catalog entry','Initial editorial profile for Stable Diffusion 36 in Research & Search.',(select id from category_map where slug = 'research-search'),'Core','https://example.com/stable-diffusion-36','icon-12','Free',null,true,'Teams evaluating research & search','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '35 days'),
  ('llama-37','Llama 37','Production starter catalog entry','Initial editorial profile for Llama 37 in Image Generation.',(select id from category_map where slug = 'image-generation'),'Core','https://example.com/llama-37','icon-1','Freemium',16.00,true,'Teams evaluating image generation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '36 days'),
  ('mistral-38','Mistral 38','Production starter catalog entry','Initial editorial profile for Mistral 38 in Video Generation.',(select id from category_map where slug = 'video-generation'),'Core','https://example.com/mistral-38','icon-2','Paid',17.00,false,'Teams evaluating video generation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '37 days'),
  ('huggingface-39','Hugging Face 39','Production starter catalog entry','Initial editorial profile for Hugging Face 39 in Voice, Audio & Music.',(select id from category_map where slug = 'voice-audio-music'),'Core','https://example.com/huggingface-39','icon-3','Open Source',null,true,'Teams evaluating voice, audio & music','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '38 days'),
  ('n8n-ai-40','n8n AI 40','Production starter catalog entry','Initial editorial profile for n8n AI 40 in Agents & Automation.',(select id from category_map where slug = 'agents-automation'),'Core','https://example.com/n8n-ai-40','icon-4','Enterprise',19.00,false,'Teams evaluating agents & automation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '39 days'),
  ('chatgpt-41','ChatGPT 41','Production starter catalog entry','Initial editorial profile for ChatGPT 41 in Productivity.',(select id from category_map where slug = 'productivity'),'Core','https://example.com/chatgpt-41','icon-5','Free',null,true,'Teams evaluating productivity','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,true,false,now() - interval '40 days'),
  ('claude-42','Claude 42','Production starter catalog entry','Initial editorial profile for Claude 42 in Design & UI.',(select id from category_map where slug = 'design-ui'),'Core','https://example.com/claude-42','icon-6','Freemium',21.00,true,'Teams evaluating design & ui','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '41 days'),
  ('gemini-43','Gemini 43','Production starter catalog entry','Initial editorial profile for Gemini 43 in Marketing & Writing.',(select id from category_map where slug = 'marketing-writing'),'Core','https://example.com/gemini-43','icon-7','Paid',22.00,false,'Teams evaluating marketing & writing','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,true,now() - interval '42 days'),
  ('grok-44','Grok 44','Production starter catalog entry','Initial editorial profile for Grok 44 in Education.',(select id from category_map where slug = 'education'),'Core','https://example.com/grok-44','icon-8','Open Source',null,true,'Teams evaluating education','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '43 days'),
  ('perplexity-45','Perplexity 45','Production starter catalog entry','Initial editorial profile for Perplexity 45 in Data Analysis.',(select id from category_map where slug = 'data-analysis'),'Core','https://example.com/perplexity-45','icon-9','Enterprise',24.00,false,'Teams evaluating data analysis','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '44 days'),
  ('cursor-46','Cursor 46','Production starter catalog entry','Initial editorial profile for Cursor 46 in Open-Source Models.',(select id from category_map where slug = 'open-source-models'),'Core','https://example.com/cursor-46','icon-10','Free',null,true,'Teams evaluating open-source models','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '45 days'),
  ('windsurf-47','Windsurf 47','Production starter catalog entry','Initial editorial profile for Windsurf 47 in AI Infrastructure & APIs.',(select id from category_map where slug = 'ai-infrastructure-apis'),'Core','https://example.com/windsurf-47','icon-11','Freemium',26.00,true,'Teams evaluating ai infrastructure & apis','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '46 days'),
  ('midjourney-48','Midjourney 48','Production starter catalog entry','Initial editorial profile for Midjourney 48 in Business & Enterprise.',(select id from category_map where slug = 'business-enterprise'),'Core','https://example.com/midjourney-48','icon-12','Paid',27.00,false,'Teams evaluating business & enterprise','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '47 days'),
  ('runway-49','Runway 49','Production starter catalog entry','Initial editorial profile for Runway 49 in Chatbots & General LLMs.',(select id from category_map where slug = 'chatbots-general-llms'),'Core','https://example.com/runway-49','icon-1','Open Source',null,true,'Teams evaluating chatbots & general llms','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '48 days'),
  ('copilot-50','GitHub Copilot 50','Production starter catalog entry','Initial editorial profile for GitHub Copilot 50 in Coding Assistants.',(select id from category_map where slug = 'coding-assistants'),'Core','https://example.com/copilot-50','icon-2','Enterprise',29.00,false,'Teams evaluating coding assistants','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '49 days'),
  ('notion-ai-51','Notion AI 51','Production starter catalog entry','Initial editorial profile for Notion AI 51 in AI IDEs.',(select id from category_map where slug = 'ai-ides'),'Core','https://example.com/notion-ai-51','icon-3','Free',null,true,'Teams evaluating ai ides','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,true,false,now() - interval '50 days'),
  ('jasper-52','Jasper 52','Production starter catalog entry','Initial editorial profile for Jasper 52 in Research & Search.',(select id from category_map where slug = 'research-search'),'Core','https://example.com/jasper-52','icon-4','Freemium',6.00,true,'Teams evaluating research & search','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '51 days'),
  ('canva-ai-53','Canva AI 53','Production starter catalog entry','Initial editorial profile for Canva AI 53 in Image Generation.',(select id from category_map where slug = 'image-generation'),'Core','https://example.com/canva-ai-53','icon-5','Paid',7.00,false,'Teams evaluating image generation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '52 days'),
  ('suno-54','Suno 54','Production starter catalog entry','Initial editorial profile for Suno 54 in Video Generation.',(select id from category_map where slug = 'video-generation'),'Core','https://example.com/suno-54','icon-6','Open Source',null,true,'Teams evaluating video generation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '53 days'),
  ('elevenlabs-55','ElevenLabs 55','Production starter catalog entry','Initial editorial profile for ElevenLabs 55 in Voice, Audio & Music.',(select id from category_map where slug = 'voice-audio-music'),'Core','https://example.com/elevenlabs-55','icon-7','Enterprise',9.00,false,'Teams evaluating voice, audio & music','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '54 days'),
  ('stable-diffusion-56','Stable Diffusion 56','Production starter catalog entry','Initial editorial profile for Stable Diffusion 56 in Agents & Automation.',(select id from category_map where slug = 'agents-automation'),'Core','https://example.com/stable-diffusion-56','icon-8','Free',null,true,'Teams evaluating agents & automation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '55 days'),
  ('llama-57','Llama 57','Production starter catalog entry','Initial editorial profile for Llama 57 in Productivity.',(select id from category_map where slug = 'productivity'),'Core','https://example.com/llama-57','icon-9','Freemium',11.00,true,'Teams evaluating productivity','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,true,now() - interval '56 days'),
  ('mistral-58','Mistral 58','Production starter catalog entry','Initial editorial profile for Mistral 58 in Design & UI.',(select id from category_map where slug = 'design-ui'),'Core','https://example.com/mistral-58','icon-10','Paid',12.00,false,'Teams evaluating design & ui','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '57 days'),
  ('huggingface-59','Hugging Face 59','Production starter catalog entry','Initial editorial profile for Hugging Face 59 in Marketing & Writing.',(select id from category_map where slug = 'marketing-writing'),'Core','https://example.com/huggingface-59','icon-11','Open Source',null,true,'Teams evaluating marketing & writing','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '58 days'),
  ('n8n-ai-60','n8n AI 60','Production starter catalog entry','Initial editorial profile for n8n AI 60 in Education.',(select id from category_map where slug = 'education'),'Core','https://example.com/n8n-ai-60','icon-12','Enterprise',14.00,false,'Teams evaluating education','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '59 days'),
  ('chatgpt-61','ChatGPT 61','Production starter catalog entry','Initial editorial profile for ChatGPT 61 in Data Analysis.',(select id from category_map where slug = 'data-analysis'),'Core','https://example.com/chatgpt-61','icon-1','Free',null,true,'Teams evaluating data analysis','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,true,false,now() - interval '60 days'),
  ('claude-62','Claude 62','Production starter catalog entry','Initial editorial profile for Claude 62 in Open-Source Models.',(select id from category_map where slug = 'open-source-models'),'Core','https://example.com/claude-62','icon-2','Freemium',16.00,true,'Teams evaluating open-source models','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '61 days'),
  ('gemini-63','Gemini 63','Production starter catalog entry','Initial editorial profile for Gemini 63 in AI Infrastructure & APIs.',(select id from category_map where slug = 'ai-infrastructure-apis'),'Core','https://example.com/gemini-63','icon-3','Paid',17.00,false,'Teams evaluating ai infrastructure & apis','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '62 days'),
  ('grok-64','Grok 64','Production starter catalog entry','Initial editorial profile for Grok 64 in Business & Enterprise.',(select id from category_map where slug = 'business-enterprise'),'Core','https://example.com/grok-64','icon-4','Open Source',null,true,'Teams evaluating business & enterprise','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '63 days'),
  ('perplexity-65','Perplexity 65','Production starter catalog entry','Initial editorial profile for Perplexity 65 in Chatbots & General LLMs.',(select id from category_map where slug = 'chatbots-general-llms'),'Core','https://example.com/perplexity-65','icon-5','Enterprise',19.00,false,'Teams evaluating chatbots & general llms','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '64 days'),
  ('cursor-66','Cursor 66','Production starter catalog entry','Initial editorial profile for Cursor 66 in Coding Assistants.',(select id from category_map where slug = 'coding-assistants'),'Core','https://example.com/cursor-66','icon-6','Free',null,true,'Teams evaluating coding assistants','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '65 days'),
  ('windsurf-67','Windsurf 67','Production starter catalog entry','Initial editorial profile for Windsurf 67 in AI IDEs.',(select id from category_map where slug = 'ai-ides'),'Core','https://example.com/windsurf-67','icon-7','Freemium',21.00,true,'Teams evaluating ai ides','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '66 days'),
  ('midjourney-68','Midjourney 68','Production starter catalog entry','Initial editorial profile for Midjourney 68 in Research & Search.',(select id from category_map where slug = 'research-search'),'Core','https://example.com/midjourney-68','icon-8','Paid',22.00,false,'Teams evaluating research & search','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '67 days'),
  ('runway-69','Runway 69','Production starter catalog entry','Initial editorial profile for Runway 69 in Image Generation.',(select id from category_map where slug = 'image-generation'),'Core','https://example.com/runway-69','icon-9','Open Source',null,true,'Teams evaluating image generation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '68 days'),
  ('copilot-70','GitHub Copilot 70','Production starter catalog entry','Initial editorial profile for GitHub Copilot 70 in Video Generation.',(select id from category_map where slug = 'video-generation'),'Core','https://example.com/copilot-70','icon-10','Enterprise',24.00,false,'Teams evaluating video generation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '69 days'),
  ('notion-ai-71','Notion AI 71','Production starter catalog entry','Initial editorial profile for Notion AI 71 in Voice, Audio & Music.',(select id from category_map where slug = 'voice-audio-music'),'Core','https://example.com/notion-ai-71','icon-11','Free',null,true,'Teams evaluating voice, audio & music','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,true,true,now() - interval '70 days'),
  ('jasper-72','Jasper 72','Production starter catalog entry','Initial editorial profile for Jasper 72 in Agents & Automation.',(select id from category_map where slug = 'agents-automation'),'Core','https://example.com/jasper-72','icon-12','Freemium',26.00,true,'Teams evaluating agents & automation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '71 days'),
  ('canva-ai-73','Canva AI 73','Production starter catalog entry','Initial editorial profile for Canva AI 73 in Productivity.',(select id from category_map where slug = 'productivity'),'Core','https://example.com/canva-ai-73','icon-1','Paid',27.00,false,'Teams evaluating productivity','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '72 days'),
  ('suno-74','Suno 74','Production starter catalog entry','Initial editorial profile for Suno 74 in Design & UI.',(select id from category_map where slug = 'design-ui'),'Core','https://example.com/suno-74','icon-2','Open Source',null,true,'Teams evaluating design & ui','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '73 days'),
  ('elevenlabs-75','ElevenLabs 75','Production starter catalog entry','Initial editorial profile for ElevenLabs 75 in Marketing & Writing.',(select id from category_map where slug = 'marketing-writing'),'Core','https://example.com/elevenlabs-75','icon-3','Enterprise',29.00,false,'Teams evaluating marketing & writing','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '74 days'),
  ('stable-diffusion-76','Stable Diffusion 76','Production starter catalog entry','Initial editorial profile for Stable Diffusion 76 in Education.',(select id from category_map where slug = 'education'),'Core','https://example.com/stable-diffusion-76','icon-4','Free',null,true,'Teams evaluating education','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '75 days'),
  ('llama-77','Llama 77','Production starter catalog entry','Initial editorial profile for Llama 77 in Data Analysis.',(select id from category_map where slug = 'data-analysis'),'Core','https://example.com/llama-77','icon-5','Freemium',6.00,true,'Teams evaluating data analysis','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '76 days'),
  ('mistral-78','Mistral 78','Production starter catalog entry','Initial editorial profile for Mistral 78 in Open-Source Models.',(select id from category_map where slug = 'open-source-models'),'Core','https://example.com/mistral-78','icon-6','Paid',7.00,false,'Teams evaluating open-source models','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '77 days'),
  ('huggingface-79','Hugging Face 79','Production starter catalog entry','Initial editorial profile for Hugging Face 79 in AI Infrastructure & APIs.',(select id from category_map where slug = 'ai-infrastructure-apis'),'Core','https://example.com/huggingface-79','icon-7','Open Source',null,true,'Teams evaluating ai infrastructure & apis','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '78 days'),
  ('n8n-ai-80','n8n AI 80','Production starter catalog entry','Initial editorial profile for n8n AI 80 in Business & Enterprise.',(select id from category_map where slug = 'business-enterprise'),'Core','https://example.com/n8n-ai-80','icon-8','Enterprise',9.00,false,'Teams evaluating business & enterprise','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '79 days'),
  ('chatgpt-81','ChatGPT 81','Production starter catalog entry','Initial editorial profile for ChatGPT 81 in Chatbots & General LLMs.',(select id from category_map where slug = 'chatbots-general-llms'),'Core','https://example.com/chatgpt-81','icon-9','Free',null,true,'Teams evaluating chatbots & general llms','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,true,false,now() - interval '80 days'),
  ('claude-82','Claude 82','Production starter catalog entry','Initial editorial profile for Claude 82 in Coding Assistants.',(select id from category_map where slug = 'coding-assistants'),'Core','https://example.com/claude-82','icon-10','Freemium',11.00,true,'Teams evaluating coding assistants','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '81 days'),
  ('gemini-83','Gemini 83','Production starter catalog entry','Initial editorial profile for Gemini 83 in AI IDEs.',(select id from category_map where slug = 'ai-ides'),'Core','https://example.com/gemini-83','icon-11','Paid',12.00,false,'Teams evaluating ai ides','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '82 days'),
  ('grok-84','Grok 84','Production starter catalog entry','Initial editorial profile for Grok 84 in Research & Search.',(select id from category_map where slug = 'research-search'),'Core','https://example.com/grok-84','icon-12','Open Source',null,true,'Teams evaluating research & search','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '83 days'),
  ('perplexity-85','Perplexity 85','Production starter catalog entry','Initial editorial profile for Perplexity 85 in Image Generation.',(select id from category_map where slug = 'image-generation'),'Core','https://example.com/perplexity-85','icon-1','Enterprise',14.00,false,'Teams evaluating image generation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,true,now() - interval '84 days'),
  ('cursor-86','Cursor 86','Production starter catalog entry','Initial editorial profile for Cursor 86 in Video Generation.',(select id from category_map where slug = 'video-generation'),'Core','https://example.com/cursor-86','icon-2','Free',null,true,'Teams evaluating video generation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '85 days'),
  ('windsurf-87','Windsurf 87','Production starter catalog entry','Initial editorial profile for Windsurf 87 in Voice, Audio & Music.',(select id from category_map where slug = 'voice-audio-music'),'Core','https://example.com/windsurf-87','icon-3','Freemium',16.00,true,'Teams evaluating voice, audio & music','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '86 days'),
  ('midjourney-88','Midjourney 88','Production starter catalog entry','Initial editorial profile for Midjourney 88 in Agents & Automation.',(select id from category_map where slug = 'agents-automation'),'Core','https://example.com/midjourney-88','icon-4','Paid',17.00,false,'Teams evaluating agents & automation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '87 days'),
  ('runway-89','Runway 89','Production starter catalog entry','Initial editorial profile for Runway 89 in Productivity.',(select id from category_map where slug = 'productivity'),'Core','https://example.com/runway-89','icon-5','Open Source',null,true,'Teams evaluating productivity','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '88 days'),
  ('copilot-90','GitHub Copilot 90','Production starter catalog entry','Initial editorial profile for GitHub Copilot 90 in Design & UI.',(select id from category_map where slug = 'design-ui'),'Core','https://example.com/copilot-90','icon-6','Enterprise',19.00,false,'Teams evaluating design & ui','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '89 days'),
  ('notion-ai-91','Notion AI 91','Production starter catalog entry','Initial editorial profile for Notion AI 91 in Marketing & Writing.',(select id from category_map where slug = 'marketing-writing'),'Core','https://example.com/notion-ai-91','icon-7','Free',null,true,'Teams evaluating marketing & writing','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,true,false,now() - interval '0 days'),
  ('jasper-92','Jasper 92','Production starter catalog entry','Initial editorial profile for Jasper 92 in Education.',(select id from category_map where slug = 'education'),'Core','https://example.com/jasper-92','icon-8','Freemium',21.00,true,'Teams evaluating education','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '1 days'),
  ('canva-ai-93','Canva AI 93','Production starter catalog entry','Initial editorial profile for Canva AI 93 in Data Analysis.',(select id from category_map where slug = 'data-analysis'),'Core','https://example.com/canva-ai-93','icon-9','Paid',22.00,false,'Teams evaluating data analysis','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '2 days'),
  ('suno-94','Suno 94','Production starter catalog entry','Initial editorial profile for Suno 94 in Open-Source Models.',(select id from category_map where slug = 'open-source-models'),'Core','https://example.com/suno-94','icon-10','Open Source',null,true,'Teams evaluating open-source models','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '3 days'),
  ('elevenlabs-95','ElevenLabs 95','Production starter catalog entry','Initial editorial profile for ElevenLabs 95 in AI Infrastructure & APIs.',(select id from category_map where slug = 'ai-infrastructure-apis'),'Core','https://example.com/elevenlabs-95','icon-11','Enterprise',24.00,false,'Teams evaluating ai infrastructure & apis','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '4 days'),
  ('stable-diffusion-96','Stable Diffusion 96','Production starter catalog entry','Initial editorial profile for Stable Diffusion 96 in Business & Enterprise.',(select id from category_map where slug = 'business-enterprise'),'Core','https://example.com/stable-diffusion-96','icon-12','Free',null,true,'Teams evaluating business & enterprise','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '5 days'),
  ('llama-97','Llama 97','Production starter catalog entry','Initial editorial profile for Llama 97 in Chatbots & General LLMs.',(select id from category_map where slug = 'chatbots-general-llms'),'Core','https://example.com/llama-97','icon-1','Freemium',26.00,true,'Teams evaluating chatbots & general llms','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '6 days'),
  ('mistral-98','Mistral 98','Production starter catalog entry','Initial editorial profile for Mistral 98 in Coding Assistants.',(select id from category_map where slug = 'coding-assistants'),'Core','https://example.com/mistral-98','icon-2','Paid',27.00,false,'Teams evaluating coding assistants','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '7 days'),
  ('huggingface-99','Hugging Face 99','Production starter catalog entry','Initial editorial profile for Hugging Face 99 in AI IDEs.',(select id from category_map where slug = 'ai-ides'),'Core','https://example.com/huggingface-99','icon-3','Open Source',null,true,'Teams evaluating ai ides','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,true,now() - interval '8 days'),
  ('n8n-ai-100','n8n AI 100','Production starter catalog entry','Initial editorial profile for n8n AI 100 in Research & Search.',(select id from category_map where slug = 'research-search'),'Core','https://example.com/n8n-ai-100','icon-4','Enterprise',29.00,false,'Teams evaluating research & search','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '9 days'),
  ('chatgpt-101','ChatGPT 101','Production starter catalog entry','Initial editorial profile for ChatGPT 101 in Image Generation.',(select id from category_map where slug = 'image-generation'),'Core','https://example.com/chatgpt-101','icon-5','Free',null,true,'Teams evaluating image generation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,true,false,now() - interval '10 days'),
  ('claude-102','Claude 102','Production starter catalog entry','Initial editorial profile for Claude 102 in Video Generation.',(select id from category_map where slug = 'video-generation'),'Core','https://example.com/claude-102','icon-6','Freemium',6.00,true,'Teams evaluating video generation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '11 days'),
  ('gemini-103','Gemini 103','Production starter catalog entry','Initial editorial profile for Gemini 103 in Voice, Audio & Music.',(select id from category_map where slug = 'voice-audio-music'),'Core','https://example.com/gemini-103','icon-7','Paid',7.00,false,'Teams evaluating voice, audio & music','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '12 days'),
  ('grok-104','Grok 104','Production starter catalog entry','Initial editorial profile for Grok 104 in Agents & Automation.',(select id from category_map where slug = 'agents-automation'),'Core','https://example.com/grok-104','icon-8','Open Source',null,true,'Teams evaluating agents & automation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '13 days'),
  ('perplexity-105','Perplexity 105','Production starter catalog entry','Initial editorial profile for Perplexity 105 in Productivity.',(select id from category_map where slug = 'productivity'),'Core','https://example.com/perplexity-105','icon-9','Enterprise',9.00,false,'Teams evaluating productivity','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '14 days'),
  ('cursor-106','Cursor 106','Production starter catalog entry','Initial editorial profile for Cursor 106 in Design & UI.',(select id from category_map where slug = 'design-ui'),'Core','https://example.com/cursor-106','icon-10','Free',null,true,'Teams evaluating design & ui','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '15 days'),
  ('windsurf-107','Windsurf 107','Production starter catalog entry','Initial editorial profile for Windsurf 107 in Marketing & Writing.',(select id from category_map where slug = 'marketing-writing'),'Core','https://example.com/windsurf-107','icon-11','Freemium',11.00,true,'Teams evaluating marketing & writing','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '16 days'),
  ('midjourney-108','Midjourney 108','Production starter catalog entry','Initial editorial profile for Midjourney 108 in Education.',(select id from category_map where slug = 'education'),'Core','https://example.com/midjourney-108','icon-12','Paid',12.00,false,'Teams evaluating education','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '17 days'),
  ('runway-109','Runway 109','Production starter catalog entry','Initial editorial profile for Runway 109 in Data Analysis.',(select id from category_map where slug = 'data-analysis'),'Core','https://example.com/runway-109','icon-1','Open Source',null,true,'Teams evaluating data analysis','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '18 days'),
  ('copilot-110','GitHub Copilot 110','Production starter catalog entry','Initial editorial profile for GitHub Copilot 110 in Open-Source Models.',(select id from category_map where slug = 'open-source-models'),'Core','https://example.com/copilot-110','icon-2','Enterprise',14.00,false,'Teams evaluating open-source models','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '19 days'),
  ('notion-ai-111','Notion AI 111','Production starter catalog entry','Initial editorial profile for Notion AI 111 in AI Infrastructure & APIs.',(select id from category_map where slug = 'ai-infrastructure-apis'),'Core','https://example.com/notion-ai-111','icon-3','Free',null,true,'Teams evaluating ai infrastructure & apis','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,true,false,now() - interval '20 days'),
  ('jasper-112','Jasper 112','Production starter catalog entry','Initial editorial profile for Jasper 112 in Business & Enterprise.',(select id from category_map where slug = 'business-enterprise'),'Core','https://example.com/jasper-112','icon-4','Freemium',16.00,true,'Teams evaluating business & enterprise','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '21 days'),
  ('canva-ai-113','Canva AI 113','Production starter catalog entry','Initial editorial profile for Canva AI 113 in Chatbots & General LLMs.',(select id from category_map where slug = 'chatbots-general-llms'),'Core','https://example.com/canva-ai-113','icon-5','Paid',17.00,false,'Teams evaluating chatbots & general llms','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,true,now() - interval '22 days'),
  ('suno-114','Suno 114','Production starter catalog entry','Initial editorial profile for Suno 114 in Coding Assistants.',(select id from category_map where slug = 'coding-assistants'),'Core','https://example.com/suno-114','icon-6','Open Source',null,true,'Teams evaluating coding assistants','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '23 days'),
  ('elevenlabs-115','ElevenLabs 115','Production starter catalog entry','Initial editorial profile for ElevenLabs 115 in AI IDEs.',(select id from category_map where slug = 'ai-ides'),'Core','https://example.com/elevenlabs-115','icon-7','Enterprise',19.00,false,'Teams evaluating ai ides','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '24 days'),
  ('stable-diffusion-116','Stable Diffusion 116','Production starter catalog entry','Initial editorial profile for Stable Diffusion 116 in Research & Search.',(select id from category_map where slug = 'research-search'),'Core','https://example.com/stable-diffusion-116','icon-8','Free',null,true,'Teams evaluating research & search','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '25 days'),
  ('llama-117','Llama 117','Production starter catalog entry','Initial editorial profile for Llama 117 in Image Generation.',(select id from category_map where slug = 'image-generation'),'Core','https://example.com/llama-117','icon-9','Freemium',21.00,true,'Teams evaluating image generation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '26 days'),
  ('mistral-118','Mistral 118','Production starter catalog entry','Initial editorial profile for Mistral 118 in Video Generation.',(select id from category_map where slug = 'video-generation'),'Core','https://example.com/mistral-118','icon-10','Paid',22.00,false,'Teams evaluating video generation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '27 days'),
  ('huggingface-119','Hugging Face 119','Production starter catalog entry','Initial editorial profile for Hugging Face 119 in Voice, Audio & Music.',(select id from category_map where slug = 'voice-audio-music'),'Core','https://example.com/huggingface-119','icon-11','Open Source',null,true,'Teams evaluating voice, audio & music','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',true,true,false,false,now() - interval '28 days'),
  ('n8n-ai-120','n8n AI 120','Production starter catalog entry','Initial editorial profile for n8n AI 120 in Agents & Automation.',(select id from category_map where slug = 'agents-automation'),'Core','https://example.com/n8n-ai-120','icon-12','Enterprise',24.00,false,'Teams evaluating agents & automation','Fast onboarding, broad ecosystem','Requires workflow tuning','{Web,Mac,Windows}',false,true,false,false,now() - interval '29 days')
on conflict (slug) do update set name=excluded.name, tagline=excluded.tagline, description=excluded.description, category_id=excluded.category_id, subcategory=excluded.subcategory, website_url=excluded.website_url, logo_url=excluded.logo_url, pricing_type=excluded.pricing_type, starting_price=excluded.starting_price, free_plan=excluded.free_plan, best_for=excluded.best_for, strengths=excluded.strengths, weaknesses=excluded.weaknesses, supported_platforms=excluded.supported_platforms, open_source=excluded.open_source, api_available=excluded.api_available, featured=excluded.featured, editor_pick=excluded.editor_pick, last_verified_at=excluded.last_verified_at, updated_at=now();

insert into public.ai_tool_scores (tool_id,benchmark_score,community_score,programmer_score,design_score,ease_of_use_score,value_score,overall_score,confidence_score,scoring_version,source_note)
select t.id,
  60 + (abs(mod(hashtext(t.slug), 40))),
  55 + (abs(mod(hashtext(t.slug || 'c'), 45))),
  58 + (abs(mod(hashtext(t.slug || 'p'), 42))),
  52 + (abs(mod(hashtext(t.slug || 'd'), 46))),
  54 + (abs(mod(hashtext(t.slug || 'e'), 44))),
  50 + (abs(mod(hashtext(t.slug || 'v'), 48))),
  round((
    (60 + abs(mod(hashtext(t.slug),40))) +
    (55 + abs(mod(hashtext(t.slug || 'c'),45))) +
    (58 + abs(mod(hashtext(t.slug || 'p'),42))) +
    (52 + abs(mod(hashtext(t.slug || 'd'),46))) +
    (54 + abs(mod(hashtext(t.slug || 'e'),44))) +
    (50 + abs(mod(hashtext(t.slug || 'v'),48)))
  ) / 6.0, 2),
  70,
  'v1.0',
  'Initial editorial estimates for starter catalog; pending ongoing verification.'
from public.ai_tools t
on conflict (tool_id) do update set benchmark_score=excluded.benchmark_score, community_score=excluded.community_score, programmer_score=excluded.programmer_score, design_score=excluded.design_score, ease_of_use_score=excluded.ease_of_use_score, value_score=excluded.value_score, overall_score=excluded.overall_score, confidence_score=excluded.confidence_score, scoring_version=excluded.scoring_version, source_note=excluded.source_note, updated_at=now();

insert into public.ai_tool_pricing (tool_id,plan_name,monthly_price,annual_price,currency,billing_notes,is_current)
select t.id,'Standard',coalesce(t.starting_price,0),coalesce(t.starting_price,0)*10,'USD','Starter catalog pricing metadata',true
from public.ai_tools t
on conflict (tool_id,plan_name) do update set monthly_price=excluded.monthly_price, annual_price=excluded.annual_price, billing_notes=excluded.billing_notes, is_current=excluded.is_current, updated_at=now();

insert into public.ai_tool_benchmarks (tool_id,benchmark_name,benchmark_score,benchmark_date,source_note)
select t.id,'Editorial baseline',s.benchmark_score,current_date,'Initial verified catalog baseline measurement.'
from public.ai_tools t join public.ai_tool_scores s on s.tool_id=t.id
on conflict do nothing;

insert into public.ai_tool_trending_snapshots (tool_id,snapshot_date,trend_score,rank_delta,mention_count)
select t.id,current_date,60 + abs(mod(hashtext(t.slug || 'trend'),40)),mod(abs(hashtext(t.slug || 'delta')),11)-5,50 + abs(mod(hashtext(t.slug || 'mentions'),500))
from public.ai_tools t
on conflict (tool_id,snapshot_date) do update set trend_score=excluded.trend_score, rank_delta=excluded.rank_delta, mention_count=excluded.mention_count;
